- platform: ping
  host: 192.168.11.11
  name: 'first_floor_ping_thermostat_office'
- platform: ping
  host: 192.168.11.12
  name: 'first_floor_ping_thermostat_corridor_and_toilet'
- platform: ping
  host: 192.168.11.13
  name: 'first_floor_ping_thermostat_bathroom'
- platform: ping
  host: 192.168.11.14
  name: 'first_floor_ping_thermostat_kitchen'
- platform: ping
  host: 192.168.11.15
  name: 'first_floor_ping_thermostat_living_room'
- platform: ping
  host: 192.168.11.16
  name: 'first_floor_ping_thermostat_cellar'
- platform: ping
  host: 192.168.11.17
  name: 'first_floor_ping_thermostat_garage'