# Checks of connection local thermostat on a first floor
- platform: ping
  host: 192.168.2.12
  name: 'first_floor_ping_thermostat_corridor_and_toilet'
  scan_interval: 30
- platform: ping
  host: 192.168.2.13
  name: 'first_floor_ping_thermostat_bathroom'
  scan_interval: 30
- platform: ping
  host: 192.168.2.15
  name: 'first_floor_ping_thermostat_living_room_and_kitchen'
  scan_interval: 30
- platform: ping
  host: 192.168.2.16
  name: 'first_floor_ping_thermostat_cellar'
  scan_interval: 30
- platform: ping
  host: 192.168.2.17
  name: 'first_floor_ping_thermostat_garage'
  scan_interval: 30
