# Checks of connection local thermostat on a second floor
- platform: ping
  host: 192.168.11.24
  name: 'second_floor_ping_thermostat_bathroom'
  scan_interval: 30
- platform: ping
  host: 192.168.11.22
  name: 'second_floor_ping_thermostat_kitchen_workroom_living_and_diving_room'
  scan_interval: 30
- platform: ping
  host: 192.168.11.21
  name: 'second_floor_ping_thermostat_thomas_bedroom'
  scan_interval: 30
- platform: ping
  host: 192.168.11.25
  name: 'second_floor_ping_thermostat_north_room'
  scan_interval: 30
- platform: ping
  host: 192.168.2.27
  name: 'second_floor_ping_thermostat_middle_room'
  scan_interval: 30
- platform: ping
  host: 192.168.11.28
  name: 'second_floor_ping_thermostat_corner_room'
  scan_interval: 30
- platform: ping
  host: 192.168.11.23
  name: 'second_floor_ping_thermostat_corridor_and_toilet'
  scan_interval: 30
- platform: ping
  host: 192.168.11.26
  name: 'second_floor_ping_thermostat_parents_bedroom'
  scan_interval: 30
