- alias: 'Sets required temperature for a middle room from system'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: climate.middle_room
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
            {{ trigger.from_state and
               trigger.to_state.attributes.temperature !=
               trigger.from_state.attributes.temperature and is_state("input_boolean.mqtt_req_temp_record_from_middle_room", "off") }}
  action:
    - service: mqtt.publish
      data:
        topic: 'home/first-floor/middle-room/required-temperature-from-system'
        payload_template: "{{ state_attr('climate.middle_room','temperature') | float }}"
        qos: 2
- alias: 'Sets required temperature for a middle room from device'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.middle_room_required_temp_from_device
  condition:
    condition: template
    value_template: >
        {{ trigger.from_state and
           trigger.to_state !=
           trigger.from_state }}
  action:
    # Disable sets required temp. from system
    - service: input_boolean.turn_on
      entity_id: input_boolean.mqtt_req_temp_record_from_middle_room
    - service: climate.set_temperature
      entity_id: climate.middle_room
      data_template:
        temperature: '{{ states("sensor.middle_room_required_temp_from_device") }}'
    - delay: 
        milliseconds: 5
    - service: input_boolean.turn_off
      entity_id: input_boolean.mqtt_req_temp_record_from_middle_room