# Detection of state open window for first floor
- platform: template
  sensors:
    first_floor_detection_of_open_window_office:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_office') }}"
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_office', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}
    first_floor_detection_of_open_window_corridor_and_toilet:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_corridor_and_toilet') }}"
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_corridor_and_toilet', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}
    first_floor_detection_of_open_window_bedroom:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_bedroom') }}" 
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_bedroom', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}
    first_floor_detection_of_open_window_kitchen:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_kitchen') }}"  
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_kitchen', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}
    first_floor_detection_of_open_window_living_room:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_living_room') }}"   
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_living_room', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}
    first_floor_detection_of_open_window_cellar:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_cellar') }}"   
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_cellar', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}
    first_floor_detection_of_open_window_garage:
      friendly_name: 'Detekce otevřeného okna'
      device_class: opening
      value_template: "{{ states('input_boolean.first_floor_detection_of_open_window_garage') }}"   
      icon_template: >-
        {%- if is_state('input_boolean.first_floor_detection_of_open_window_garage', 'on') -%}
          mdi:window-open
        {%- else -%}
          mdi:window-closed
        {%- endif -%}