# Bathroom
- platform: mqtt
  name: 'second_floor_bathroom_temp'
  state_topic: 'home/second-floor/bathroom/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_bathroom_required_temp_from_device'
  state_topic: 'home/second-floor/bathroom/required-temperature-from-device'
  unit_of_measurement: '°C'
# Kitchen, workroom, living and diving room
- platform: mqtt
  name: 'second_floor_kitchen_workroom_living_and_diving_room_temp'
  state_topic: 'home/second-floor/kitchen-workroom-living-and-diving-room/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_kitchen_workroom_living_and_diving_room_required_temp_from_device'
  state_topic: 'home/second-floor/kitchen-workroom-living-and-diving-room/required-temperature-from-device'
  unit_of_measurement: '°C'
# Thomas bedroom
- platform: mqtt
  name: 'second_floor_thomas_bedroom_temp'
  state_topic: 'home/second-floor/thomas-bedroom/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_thomas_bedroom_required_temp_from_device'
  state_topic: 'home/second-floor/thomas-bedroom/required-temperature-from-device'
  unit_of_measurement: '°C'
# North room
- platform: mqtt
  name: 'second_floor_north_room_temp'
  state_topic: 'home/second-floor/north-room/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_north_room_required_temp_from_device'
  state_topic: 'home/second-floor/north-room/required-temperature-from-device'
  unit_of_measurement: '°C'
# Middle room
- platform: mqtt
  name: 'second_floor_middle_room_temp'
  state_topic: 'home/second-floor/middle-room/temperature'
  unit_of_measurement: '°C'
  qos: 2
- platform: mqtt
  name: 'second_floor_middle_room_required_temp_from_device'
  state_topic: 'home/second-floor/middle-room/required-temperature-from-device'
  unit_of_measurement: '°C'
  qos: 2
# Corner room
- platform: mqtt
  name: 'second_floor_corner_room_temp'
  state_topic: 'home/second-floor/corner-room/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_corner_room_required_temp_from_device'
  state_topic: 'home/second-floor/corner-room/required-temperature-from-device'
  unit_of_measurement: '°C'
# Corridor and toilet
- platform: mqtt
  name: 'second_floor_corridor_and_toilet_temp'
  state_topic: 'home/second-floor/corridor-and-toilet/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_corridor_and_toilet_required_temp_from_device'
  state_topic: 'home/second-floor/corridor-and-toilet/required-temperature-from-device'
  unit_of_measurement: '°C'
# Parents bedroom
- platform: mqtt
  name: 'second_floor_parents_bedroom_temp'
  state_topic: 'home/second-floor/parents-bedroom/temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'second_floor_parents_bedroom_required_temp_from_device'
  state_topic: 'home/second-floor/parents-bedroom/required-temperature-from-device'
  unit_of_measurement: '°C'