# Checks of connection local thermostat on a first floor
- platform: template
  sensors:
    first_floor_connection_of_thermostat_corridor_and_toilet:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.first_floor_corridor_and_toilet_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.first_floor_corridor_and_toilet_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    first_floor_connection_of_thermostat_bathroom:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.first_floor_bathroom_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.first_floor_bathroom_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    first_floor_connection_of_thermostat_living_room_and_kitchen:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.first_floor_living_room_and_kitchen_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.first_floor_living_room_and_kitchen_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    first_floor_connection_of_thermostat_cellar:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.first_floor_cellar_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.first_floor_cellar_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    first_floor_connection_of_thermostat_garage:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.first_floor_garage_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.first_floor_garage_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity