# Checks of connection local thermostat on a second floor
- platform: template
  sensors:
    second_floor_connection_of_thermostat_bathroom:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_bathroom_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_bathroom_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_kitchen_workroom_living_and_diving_room:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_kitchen_workroom_living_and_diving_room_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_kitchen_workroom_living_and_diving_room_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_thomas_bedroom:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_thomas_bedroom_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_thomas_bedroom_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_north_room:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_north_room_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_north_room_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_middle_room:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_middle_room_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_middle_room_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_corner_room:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_corner_room_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_corner_room_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_corridor_and_toilet:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_corridor_and_toilet_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_corridor_and_toilet_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity
    second_floor_connection_of_thermostat_parents_bedroom:
      friendly_name: 'Stav připojení'
      value_template:  >
        {%- if not is_state('sensor.second_floor_parents_bedroom_actual_time', 'unknown') and 
        (as_timestamp(now()) - 1*60) | timestamp_custom('%H:%M:%S') < strptime(states('sensor.second_floor_parents_bedroom_actual_time'), '%H:%M:%S') -%}
          on
        {%- else -%}
          off
        {%- endif -%}
      device_class: connectivity