homeassistant:
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  resources:
    - url: /local/scheduler-card/scheduler-card.js?v=0
      type: module
  dashboards:
    lovelace-firstfloorthermostats: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboards_first_floor_thermostats.yaml
      title: 'Přízemí – termostaty'
      icon: mdi:thermostat
      show_in_sidebar: true
      require_admin: false
    lovelace-secondfloorthermostats: 
      mode: yaml
      filename: dashboards_second_floor_thermostats.yaml
      title: 'Patro – termostaty'
      icon: mdi:thermostat
      show_in_sidebar: true
      require_admin: false
    lovelace-dashboardsfirstfloortemperatureplans:
      mode: yaml
      filename: dashboards_first_floor_temperature_plans.yaml
      title: 'Přízemí – teplotní plány'
      icon: mdi:calendar-range
      show_in_sidebar: true
      require_admin: false
    lovelace-dashboardssecondfloortemperatureplans:
      mode: yaml
      filename: dashboards_second_floor_temperature_plans.yaml
      title: 'Patro – teplotní plány'
      icon: mdi:calendar-range
      show_in_sidebar: true
      require_admin: false
      
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate



recorder:
  db_url: postgresql://@/homeassistant
  purge_keep_days: 7
  include:
    domains:
      - climate
    entities:
      - sensor.hot_water_tank_top
      - sensor.hot_water_tank_middle
      - sensor.hot_water_tank_bottom
      - sensor.outdoor
      - sensor.fireplace_cellar
      - sensor.fireplace_first_floor
      - sensor.fireplace_second_floor
      - binary_sensor.temp_first_floor
      - binary_sensor.temp_second_floor
      - switch.gas_boiler
      - switch.pump_fireplace_cellar
      - switch.pump_fireplace_first_floor
      - switch.pump_fireplace_second_floor
      - switch.pump_first_floor
      - switch.pump_second_floor
      - switch.red_led
      - switch.orange_led
      - switch.blue_led
      - input_number.thermo_actuator_first_floor_office
      - input_number.thermo_actuator_first_floor_corridor_and_toiler
      - input_number.thermo_actuator_first_floor_bathroom_ladder
      - input_number.thermo_actuator_first_floor_bathroom
      - input_number.thermo_actuator_first_floor_kitchen_door
      - input_number.thermo_actuator_first_floor_living_room_1
      - input_number.thermo_actuator_first_floor_living_room_2
      - input_number.thermo_actuator_first_floor_living_room_3
      - input_number.thermo_actuator_first_floor_kitchen_windows
      - input_number.thermo_actuator_first_floor_cellar_ladder
      - input_number.thermo_actuator_first_floor_garage_1
      - input_number.thermo_actuator_first_floor_garage_2
      - input_number.thermo_actuator_second_floor_bathroom
      - input_number.thermo_actuator_second_floor_bathroom_ladder
      - input_number.thermo_actuator_second_floor_living_and_diving_room
      - input_number.thermo_actuator_second_floor_workroom
      - input_number.thermo_actuator_second_floor_kitchen
      - input_number.thermo_actuator_second_floor_thomas_bedroom
      - input_number.thermo_actuator_second_floor_north_room
      - input_number.thermo_actuator_second_floor_middle_room
      - input_number.thermo_actuator_second_floor_corner_room
      - input_number.thermo_actuator_second_floor_parents_bedroom_window
      - input_number.thermo_actuator_second_floor_parents_bedroom_door
      - input_number.thermo_actuator_second_floor_corridor_and_toilet

history:
  include:
    domains:
      - climate
    entities:
      - sensor.hot_water_tank_top
      - sensor.hot_water_tank_middle
      - sensor.hot_water_tank_bottom
      - sensor.outdoor
      - sensor.fireplace_cellar
      - sensor.fireplace_first_floor
      - sensor.fireplace_second_floor
      - binary_sensor.temp_first_floor
      - binary_sensor.temp_second_floor
      - switch.gas_boiler
      - switch.pump_fireplace_cellar
      - switch.pump_fireplace_first_floor
      - switch.pump_fireplace_second_floor
      - switch.pump_first_floor
      - switch.pump_second_floor
      - switch.red_led
      - switch.orange_led
      - switch.blue_led
      - input_number.thermo_actuator_first_floor_office
      - input_number.thermo_actuator_first_floor_corridor_and_toiler
      - input_number.thermo_actuator_first_floor_bathroom_ladder
      - input_number.thermo_actuator_first_floor_bathroom
      - input_number.thermo_actuator_first_floor_kitchen_door
      - input_number.thermo_actuator_first_floor_living_room_1
      - input_number.thermo_actuator_first_floor_living_room_2
      - input_number.thermo_actuator_first_floor_living_room_3
      - input_number.thermo_actuator_first_floor_kitchen_windows
      - input_number.thermo_actuator_first_floor_cellar_ladder
      - input_number.thermo_actuator_first_floor_garage_1
      - input_number.thermo_actuator_first_floor_garage_2
      - input_number.thermo_actuator_second_floor_bathroom
      - input_number.thermo_actuator_second_floor_bathroom_ladder
      - input_number.thermo_actuator_second_floor_living_and_diving_room
      - input_number.thermo_actuator_second_floor_workroom
      - input_number.thermo_actuator_second_floor_kitchen
      - input_number.thermo_actuator_second_floor_thomas_bedroom
      - input_number.thermo_actuator_second_floor_north_room
      - input_number.thermo_actuator_second_floor_middle_room
      - input_number.thermo_actuator_second_floor_corner_room
      - input_number.thermo_actuator_second_floor_parents_bedroom_window
      - input_number.thermo_actuator_second_floor_parents_bedroom_door
      - input_number.thermo_actuator_second_floor_corridor_and_toilet

logbook:
  include:
    domains:
      - climate
    entities:
      - sensor.hot_water_tank_top
      - sensor.hot_water_tank_middle
      - sensor.hot_water_tank_bottom
      - sensor.outdoor
      - sensor.fireplace_cellar
      - sensor.fireplace_first_floor
      - sensor.fireplace_second_floor
      - binary_sensor.temp_first_floor
      - binary_sensor.temp_second_floor
      - switch.gas_boiler
      - switch.pump_fireplace_cellar
      - switch.pump_fireplace_first_floor
      - switch.pump_fireplace_second_floor
      - switch.pump_first_floor
      - switch.pump_second_floor
      - switch.red_led
      - switch.orange_led
      - switch.blue_led
      - input_number.thermo_actuator_first_floor_office
      - input_number.thermo_actuator_first_floor_corridor_and_toiler
      - input_number.thermo_actuator_first_floor_bathroom_ladder
      - input_number.thermo_actuator_first_floor_bathroom
      - input_number.thermo_actuator_first_floor_kitchen_door
      - input_number.thermo_actuator_first_floor_living_room_1
      - input_number.thermo_actuator_first_floor_living_room_2
      - input_number.thermo_actuator_first_floor_living_room_3
      - input_number.thermo_actuator_first_floor_kitchen_windows
      - input_number.thermo_actuator_first_floor_cellar_ladder
      - input_number.thermo_actuator_first_floor_garage_1
      - input_number.thermo_actuator_first_floor_garage_2
      - input_number.thermo_actuator_second_floor_bathroom
      - input_number.thermo_actuator_second_floor_bathroom_ladder
      - input_number.thermo_actuator_second_floor_living_and_diving_room
      - input_number.thermo_actuator_second_floor_workroom
      - input_number.thermo_actuator_second_floor_kitchen
      - input_number.thermo_actuator_second_floor_thomas_bedroom
      - input_number.thermo_actuator_second_floor_north_room
      - input_number.thermo_actuator_second_floor_middle_room
      - input_number.thermo_actuator_second_floor_corner_room
      - input_number.thermo_actuator_second_floor_parents_bedroom_window
      - input_number.thermo_actuator_second_floor_parents_bedroom_door
      - input_number.thermo_actuator_second_floor_corridor_and_toilet

mqtt:
  broker: 192.168.11.247
  username: homeassistant
  password: VelmiSilneHesloProHomeassistant




input_number: !include_dir_merge_named input_numbers/
input_boolean: !include_dir_merge_named input_booleans/
input_datetime: !include_dir_merge_named input_datetimes/
input_select: !include_dir_merge_named input_selects/
switch: !include_dir_merge_list control_gpio_devices/
sensor: !include_dir_merge_list sensors/
climate: !include_dir_merge_list climates/

automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
group: !include_dir_merge_named groups/
shell_command: !include shell_command.yaml

