homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

recorder:
  db_url: postgresql://@/homeassistant
  purge_keep_days: 3
  include:
    entities:
      - sensor.hot_water_tank_top
      - sensor.hot_water_tank_middle
      - sensor.hot_water_tank_bottom
      - sensor.outdoor_temperature
      - sensor.fireplace_first_floor
      - sensor.fireplace_second_floor
      - binary_sensor.temp_first_floor
      - binary_sensor.temp_second_floor
      - switch.gas_boiler
      - switch.pump_fireplace_first_floor
      - switch.pump_fireplace_second_floor
      - switch.pump_first_floor
      - switch.pump_second_floor
      - switch.red_led
      - switch.orange_led
      - switch.blue_led

history:
  include:
    entities:
      - sensor.hot_water_tank_top
      - sensor.hot_water_tank_middle
      - sensor.hot_water_tank_bottom
      - sensor.outdoor_temperature
      - sensor.fireplace_first_floor
      - sensor.fireplace_second_floor
      - binary_sensor.temp_first_floor
      - binary_sensor.temp_second_floor
      - switch.gas_boiler
      - switch.pump_fireplace_first_floor
      - switch.pump_fireplace_second_floor
      - switch.pump_first_floor
      - switch.pump_second_floor
      - switch.red_led
      - switch.orange_led
      - switch.blue_led

logbook:
  include:
    entities:
      - sensor.hot_water_tank_top
      - sensor.hot_water_tank_middle
      - sensor.hot_water_tank_bottom
      - sensor.outdoor_temperature
      - sensor.fireplace_first_floor
      - sensor.fireplace_second_floor
      - binary_sensor.temp_first_floor
      - binary_sensor.temp_second_floor
      - switch.gas_boiler
      - switch.pump_fireplace_first_floor
      - switch.pump_fireplace_second_floor
      - switch.pump_first_floor
      - switch.pump_second_floor
      - switch.red_led
      - switch.orange_led
      - switch.blue_led

input_number: !include_dir_merge_named input_numbers/
input_boolean: !include_dir_merge_named input_booleans/
switch: !include_dir_merge_list control_gpio_devices/

sensor: !include_dir_merge_list sensors/

automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/

