views:
  - title: 'Nastavení'
    path: nastaveni
    cards:
      - type: horizontal-stack
        title: 'Módy řízení'
        cards:
          - type: entity-button
            entity: input_boolean.manual_summer_mode
          - type: entity-button
            entity: input_boolean.manual_winter_mode
          - type: entity-button
            entity: input_boolean.control_mode_from_outdoor_temp_sensor
      - type: entities
        title: 'Řízení podle snímaní teploty'
        show_header_toggle: false
        entities:
          - input_boolean.manual_control_corridor_thermostat
          - input_boolean.manual_control_room_thermostat
      - type: horizontal-stack
        title: 'Spínání plynového kotle'
        cards:
          - type: glance
            title: 'Léto'
            entities:
              - input_number.gas_boiler_summer_temp_from
              - input_number.gas_boiler_summer_temp_to
          - type: glance
            title: 'Zima'
            entities:
              - input_number.gas_boiler_winter_temp_from
              - input_number.gas_boiler_winter_temp_to
      - type: glance
        title: 'Krby – spínání čerpadel'
        entities:
          - input_number.fireplace_cellar_min_temp_value
          - input_number.fireplace_first_floor_min_temp_value
          - input_number.fireplace_second_floor_min_temp_value
      - type: glance
        title: 'LED indikace – mezní parametry zásobníku teplé vody'
        entities:
          - input_number.led_indication_min_value_temp_top_sensor
          - input_number.led_indication_max_value_temp_middle_sensor
          - input_number.led_indication_max_value_temp_bottom_sensor
      - type: glance
        title: 'Ostatní nastavení'
        entities:
          - input_number.gas_boiler_temp_hysteresis
          - input_number.min_temp_summer_mode
      - type: vertical-stack
        title: 'Teploty'
        cards:
          - type: history-graph
            title: 'Porovnání teploty'
            entities:
              - entity: sensor.hot_water_tank_top
              - entity: sensor.hot_water_tank_middle
              - entity: sensor.hot_water_tank_bottom
              - entity: sensor.fireplace_cellar
              - entity: sensor.fireplace_first_floor
              - entity: sensor.fireplace_second_floor
              - entity: sensor.outdoor
          - type: entities
            title: 'Jednotlivé sensory'
            show_header_toggle: false
            entities:
              - entity: sensor.hot_water_tank_top
              - entity: sensor.hot_water_tank_middle
              - entity: sensor.hot_water_tank_bottom
              - entity: sensor.fireplace_cellar
              - entity: sensor.fireplace_first_floor
              - entity: sensor.fireplace_second_floor
              - entity: sensor.outdoor     
  - title: 'Zařízení'
    path: zarizeni
    cards:
      - type: entities
        title: 'Koncová zařízení'
        show_header_toggle: false
        entities:
          - input_boolean.manual_control_devices
          - entity: switch.gas_boiler
          - entity: switch.pump_fireplace_cellar
          - entity: switch.pump_fireplace_first_floor
          - entity: switch.pump_fireplace_second_floor
          - entity: switch.pump_first_floor
          - entity: switch.pump_second_floor
          - sensor.blue_led
          - sensor.orange_led
          - sensor.red_led
      - type: glance
        title: 'Termostaty chodby – požadavek topení'
        entities:
          - sensor.thermostat_first_floor_display
          - sensor.thermostat_second_floor_display
      - type: entities
        title: 'Ovládání čerpadel – vodní kámen'
        entities: 
          - input_boolean.pumps_auto_start_cleaning
          - input_select.pumps_start_cleaning
          - input_datetime.pumps_start_cleaning
          - input_number.pumps_lenght_of_run
      - type: entities
        title: 'Nastavení pohonů okruhů podla. vytápění'
        show_header_toggle: false
        entities:
          - input_number.thermo_actuator_bathroom
          - input_number.thermo_actuator_bathroom_ladder
          - input_number.thermo_actuator_living_and_diving_room
          - input_number.thermo_actuator_workroom
          - input_number.thermo_actuator_kitchen
          - input_number.thermo_actuator_corridor_and_toilet
          - input_number.thermo_actuator_north_room
          - input_number.thermo_actuator_parents_bedroom_window
          - input_number.thermo_actuator_parents_bedroom_door
          - input_number.thermo_actuator_middle_room
          - input_number.thermo_actuator_corner_room
          - input_number.thermo_actuator_thomas_bedroom
     
  - title: 'Termostaty'
    path: termostaty
    cards:
      - type: thermostat
        entity: climate.bathroom
        name: 'Koupelna'
      - type: thermostat
        entity: climate.kitchen_workroom_living_and_diving_room
        name: 'Kuchyň, pracovna, obývací/jidelní pokoj'
      - type: thermostat
        entity: climate.thomas_bedroom
        name: 'Tomáš ložnice'
      - type: thermostat
        entity: climate.north_room
        name: 'Severní pokoj'
      - type: thermostat
        entity: climate.middle_room
        name: 'Střední pokoj'
      - type: thermostat
        entity: climate.corner_room
        name: 'Rohový pokoj'
      - type: thermostat
        entity: climate.corridor_and_toilet
        name: 'Chodba a toaleta'
      - type: thermostat
        entity: climate.parents_bedroom
        name: 'Ložnice rodičů'
  - title: 'Ovládání RPi'
    path: ovladani-rpi
    cards:
    - type: entities
      title: 'Ovládání RPi'
      show_header_toggle: false
      entities:
        - script.shutdown_rpi
        - script.restart_rpi
    