- platform: rpi_gpio
  ports:
    18: gas_boiler
    23: pump_fireplace_first_floor
    24: pump_fireplace_second_floor
    25: pump_first_floor
    26: pump_second_floor
    27: red_led
    28: orange_led
    29: blue_led
  invert_logic: true