- platform: rpi_gpio
  ports:
    25: gas_boiler
    17: pump_fireplace_first_floor
    27: pump_fireplace_second_floor
    22: pump_first_floor
    5: pump_second_floor
    6: red_led
    16: orange_led
    26: blue_led
  invert_logic: true