- platform: template
  sensors:
    mode_control_from_outdoor_temp_sensor:
      value_template: >
        {%- set outdoor_temperature = states('sensor.outdoor_temperature') | int -%}
        {%- set min_temp_summer_mode = states('input_number.min_temp_summer_mode') | int -%}
        {%- if is_state('input_boolean.control_mode_from_outdoor_temp_sensor', 'on') -%}
          {%- if outdoor_temperature >= min_temp_summer_mode -%}
            summer
          {%- else -%}
            winter
          {%- endif -%}
        {%- else -%}
          null
        {%- endif -%}
    mode_control_from_manual_control:
      value_template: >
        {%- if is_state('input_boolean.manual_control_mode', 'on') -%}
          {%- if is_state('input_boolean.manual_summer_mode', 'on') -%}
            summer
          {%- elif is_state('input_boolean.manual_winter_mode', 'on') -%}
            winter
          {%- else -%}
            null
          {%- endif -%}
        {%- else -%}
           null        
        {%- endif -%}
