- platform: onewire
  names:
    28-0317214ad6ff: hot_water_tank_top
    28-0316b592c9ff: hot_water_tank_middle
    28-04172166d4ff: hot_water_tank_bottom
    28-0417215f61ff: fireplace_second_floor
    28-0317214ad6ff: fireplace_first_floor
    28-0316b592c9ff: outdoor