# Sensors for thermostat
- platform: template
  sensors:
    thermostat_first_floor:
      friendly_name: 'Termostat první patro'
      value_template: '0'
    thermostat_second_floor:
      friendly_name: 'Termostat druhé patro'
      value_template: '0'