# Bathroom
- platform: generic_thermostat
  name: second_floor_bathroom
  heater: input_boolean.zone_second_floor_bathroom
  target_sensor: sensor.second_floor_bathroom_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# Kitchen, workroom, living and diving room
- platform: generic_thermostat
  name: second_floor_kitchen_workroom_living_and_diving_room
  heater: input_boolean.zone_second_floor_kitchen_workroom_living_and_diving_room
  target_sensor: sensor.second_floor_kitchen_workroom_living_and_diving_room_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# Thomas bedroom
- platform: generic_thermostat
  name: second_floor_thomas_bedroom
  heater: input_boolean.zone_second_floor_thomas_bedroom
  target_sensor: sensor.second_floor_thomas_bedroom_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# North room
- platform: generic_thermostat
  name: second_floor_north_room
  heater: input_boolean.zone_second_floor_north_room
  target_sensor: sensor.second_floor_north_room_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# Middle room
- platform: generic_thermostat
  name: second_floor_middle_room
  heater: input_boolean.zone_second_floor_middle_room
  target_sensor: sensor.second_floor_middle_room_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# Corner room
- platform: generic_thermostat
  name: second_floor_corner_room
  heater: input_boolean.zone_second_floor_corner_room
  target_sensor: sensor.second_floor_corner_room_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# Corridor and toilet
- platform: generic_thermostat
  name: second_floor_corridor_and_toilet
  heater: input_boolean.zone_second_floor_corridor_and_toilet
  target_sensor: sensor.second_floor_corridor_and_toilet_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5
# Parents bedroom
- platform: generic_thermostat
  name: second_floor_parents_bedroom
  heater: input_boolean.zone_second_floor_parents_bedroom
  target_sensor: sensor.second_floor_parents_bedroom_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: 'heat'
  away_temp: 16
  precision: 0.5