- platform: generic_thermostat
  name: parents_bedroom
  heater: input_boolean.zone_parents_bedroom
  target_sensor: sensor.parents_bedroom_temp
  min_temp: 0
  max_temp: 30
  ac_mode: false
  target_temp: 20
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1