- platform: template
  sensors:
    second_floor_corridor_and_toilet_forecast:
      value_template: >
        {%- set roomTemperature = states('sensor.second_floor_corridor_and_toilet_temp') | float -%}
        {%- set requiredTemperature = state_attr('climate.second_floor_corridor_and_toilet', 'temperature') | float -%}
        {%- set nextStartTimeSlotMinutes = states('input_number.second_floor_corridor_and_toilet_next_start') | int -%}
        {%- set currentStartTimeSlotMinutes = states('input_number.second_floor_corridor_and_toilet_current_start') | int -%}
        {%- set currentMinutes = (now().hour * 60 + now().minute) | int -%}
        {%- set hourForForecast = (nextStartTimeSlotMinutes/60) | int -%}
        {%- set forecastTemperature = state_attr('weather.home_hourly', 'forecast')[hourForForecast].temperature | float -%}
        {%- set outdoorTemperature = states('sensor.outdoor') | float -%}
        {%- set slope = states('input_number.second_floor_corridor_and_toilet_slope') | float -%}
        {%- set intercept = states('input_number.second_floor_corridor_and_toilet_intercept') | float -%}
        {%- set nextLinearApproximation = ((roomTemperature - forecastTemperature) * slope - intercept) | int -%}
        {%- set currentLinearApproximation = ((roomTemperature - outdoorTemperature) * slope - intercept) | int -%}
        {%- set diffTime = (nextStartTimeSlotMinutes - currentMinutes) | int -%} 
        {%- if is_state('input_boolean.control_according_to_plans_with_temperature_prediction','on') -%} 
          {%- if nextLinearApproximation >= 0 -%}  
            {%- if diffTime >= 0 and diffTime <= nextLinearApproximation -%}
              heating
            {%- else -%}
              off
            {%- endif -%}
          {%- elif currentLinearApproximation < 0 -%}
            {%- if currentMinutes >= currentStartTimeSlotMinutes and currentMinutes <= currentStartTimeSlotMinutes + (-1 * currentLinearApproximation) -%}
              not_heating
            {%- else -%}
              off
            {%- endif -%}
          {%- else -%}
              off
          {%- endif -%}
        {%- else -%}
          off
        {%- endif -%}

