- alias: 'Control mode according to manual control'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.manual_control_mode
    to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.control_mode_from_outdoor_temp_sensor
- alias: 'Control mode from outdoor temp. sensor'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.control_mode_from_outdoor_temp_sensor
    to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.manual_control_mode
        - input_boolean.manual_summer_mode
        - input_boolean.manual_winter_mode

- alias: 'Manual winter control'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.manual_winter_mode
    to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.manual_control_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.manual_summer_mode
- alias: 'Manual summer control'
  initial_state: 'on'
   condition:
    condition: state
    entity_id: input_boolean.manual_control_mode
    state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.manual_control_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.manual_winter_mode