# Refresh every 5 second, checks changes
- alias: 'Main loop all script'
  initial_state: 'on'
  trigger:
    platform: time_pattern
    seconds: '/5'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {%- if is_state('input_boolean.manual_control_corridor_thermostat', 'on') -%}
            script.hot_water_tank_top_sensor_gas_boiler, 
            script.temp_corridor_first_floor, 
            script.temp_corridor_second_floor, 
            script.fireplace_cellar_temp_sensor, 
            script.fireplace_first_floor_temp_sensor, 
            script.fireplace_second_floor_temp_sensor, 
            script.hot_water_tank_top_sensor_led_indication, 
            script.hot_water_tank_middle_sensor_led_indication, 
            script.hot_water_tank_bottom_sensor_led_indication
          {%- else -%}
            script.set_actuators,
            script.hot_water_tank_top_sensor_gas_boiler, 
            script.fireplace_cellar_temp_sensor, 
            script.fireplace_first_floor_temp_sensor, 
            script.fireplace_second_floor_temp_sensor, 
            script.hot_water_tank_top_sensor_led_indication, 
            script.hot_water_tank_middle_sensor_led_indication, 
            script.hot_water_tank_bottom_sensor_led_indication
          {%- endif -%}
        